import type { Theme } from './types';

export const darkTheme: Theme = {
  colors: {
    primary: '#3B82F6',
    secondary: '#94A3B8',
    success: '#22C55E',
    danger: '#EF4444',
    warning: '#FBBF24',
    info: '#38BDF8',
    light: '#1E293B',
    dark: '#F8FAFC',
    disabled: '#64748B',
    background: '#0F172A',
    surface: '#1E293B',
  },
  typography: {
    fontFamily: 'Inter, sans-serif',
    fontSize: {
      xs: '12px',
      sm: '14px',
      md: '16px',
      lg: '18px',
      xl: '20px',
      xxl: '22px',
    },
    fontWeight: {
      light: 300,
      regular: 400,
      medium: 500,
      bold: 700,
    },
    lineHeight: {
      xs: '12px',
      sm: '14px',
      md: '16px',
      lg: '18px',
      xl: '20px',
      xxl: '22px',
    },
  },
  spacing: {
    xs: '12px',
    sm: '14px',
    md: '16px',
    lg: '18px',
    xl: '20px',
    xxl: '22px',
  },
  borderRadius: {
    xs: '12px',
    sm: '14px',
    md: '16px',
    lg: '18px',
    xl: '20px',
    xxl: '22px',
  },
  boxShadow: {
    xs: '12px',
    sm: '14px',
    md: '16px',
    lg: '18px',
    xl: '20px',
    xxl: '22px',
  },
  breakpoints: {
    xs: '12px',
    sm: '14px',
    md: '16px',
    lg: '18px',
    xl: '20px',
    xxl: '22px',
  },
};
